### ISSUE TITLE
Express middleware error - TypeError: View is not a constructor create-app.js:121

### ISSUE THREAD

**Issue by kevzettler** [ericrglass/fastify-normalize-request-reply#2]
## 🐛 Bug Report

I'm trying to use an express middleware https://github.com/vcapretz/bull-board in a fastify server.

Fastify is throwing the following error from fastify-normalize-request-reply

```
ypeError: View is not a constructor
    at Object.render (/Users/kevzettler/code/geneva/talk-node/node_modules/fastify-normalize-request-reply/create-app.js:121:14)
    at ServerResponse.render (/Users/kevzettler/code/geneva/talk-node/node_modules/fastify-normalize-request-reply/normalize-reply.js:998:9)
    at module.exports (/Users/kevzettler/code/geneva/talk-node/node_modules/bull-board/routes/index.js:3:7)
    at /Users/kevzettler/code/geneva/talk-node/node_modules/express-async-router/index.js:92:32
    at Layer.handle [as handle_request] (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/index.js:335:12)
```

This is stemming from this line:

https://github.com/ericrglass/fastify-normalize-request-reply/blob/master/create-app.js#L119

What does this plugin expect that `app.get('view')` value to be?

**Comment by ericrglass** [comment]
What version of fastify, so I can give it a try. I have not worked on this
middleware for a while.

**Comment by ericrglass** [comment]
Created a test project with fastify and the middleware, which included bull-board; and reproduced the issue. After looking into the source of the bull-board middleware it was found that it is creating its own instance of the Express server with a view template engine. I have updated this middleware README with a note that it is only for simple Express middleware that interacts with the request and response. I have update this middleware to log to the console a warning and suggest setting up the fastify point-of-view middleware to support view template engines.
